[package]
name = "deps"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
regex = "1.6"
rand = "*"
# chrono = "0.4"
time = { version = "0.3", features = ["serde"] }
# flume = "0.10"
once_cell = "1.8"
parking_lot = "*"
# parking_lot = { version = "0.11", features = ["nightly"] }
# bitflags = "*"
# downcast-rs = "1.2"
# itertools = "*"

# smallvec = { version = "1.6", features = ["serde", "const_generics", "const_new", "union"] }
# smartstring = { version = "1", features = ["serde"] }

educe = "0.4"
# derivative = { version = "2.2.0", }

thiserror = "1.0.3"
tracing-error = "0.2"
tracing-unwrap = "0.9"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1.9"

color-eyre = "0.6.0"
tracing = "0.1"
tracing-subscriber = {version = "0.3.9", features = ["env-filter", "parking_lot"]}
tracing-appender = "0.2.2"
tracing-futures = "0.2"

async-trait = "*"
futures = "0.3" 
# futures-lite = "1.11"
tokio = { version = "1", features = ["full", "parking_lot"] }
tokio-stream = "0.1"

axum = "0.5"
tower = { version = "*", features = [] }
tower-http = { version = "*", features = ["full"] }
hyper = { version = "*", features = ["server", "tcp", "stream", "http1"] }

utoipa = { version = "2", features = ["debug", "uuid", "time", "smallvec", "axum_extras"] }
utoipa-swagger-ui = { version = "2", features = ["axum"] }
uuid = { version = "1", features = ["v4", "fast-rng", "serde"] }

# config = { version = "0.13", features = ["toml"] }
dotenvy = "0.15"

argon2 = { package = "rust-argon2", version = "1.0.0" }
brotli = "*"
base64 = "*"

redis = { version = "0.21", features = ["tokio-comp", "tokio-native-tls-comp", "streams", "connection-manager"] }
bb8-redis = "0.11"

[build-dependencies]
cargo_toml = "0.11"
toml = "*"
