[package]
name = "deps"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
# regex = "1.5.5"
# rand = "0.8"
# chrono = "0.4"
# flume = "0.10"
once_cell = "1.8"
parking_lot = "*"
# parking_lot = { version = "0.11", features = ["nightly"] }
# bitflags = "1.2"
# downcast-rs = "1.2"
# itertools = "0.10.3"

# smallvec = { version = "1.6", features = ["serde", "const_generics", "const_new", "union"] }
# smartstring = "1.0.1"

educe = "0.4"
# derivative = { version = "2.2.0", }

thiserror = "1.0.3"
tracing-error = "0.2"
tracing-unwrap = "0.9"

# serde = { version = "1", features = ["derive"] }
# serde_repr = { version = "0.1" }

color-eyre = "0.6.0"
tracing = "0.1"
tracing-subscriber = {version = "0.3.9", features = ["env-filter", "parking_lot"]}
tracing-appender = "0.2.2"
tracing-futures = "0.2"

# futures = "0.3" 
# # futures-lite = "1.11"
# tokio = { version = "1", features = ["full", "parking_lot"] }
# tokio-stream = "0.1"


[build-dependencies]
cargo_toml = "0.11"
toml = "*"
