version: "3.9"

# this just launches posrgres and redis and exposes the ports locally
# TODO: use devcontainer to develop inside the container
services:
  web:
    profiles:
      - disabled
    restart: "no"
    deploy:
      replicas: 0 # disable the api.
    #image: registry.heroku.com/my-rust-api/web
  postgres:
    container_name: postgres-server-dev
    env_file:
      - .env
    ports:
      - "5432:5432"
  swagger-editor:
    container_name: swagger-editor
    image: docker.io/swaggerapi/swagger-editor
    volumes:
      - ./api.oas3.json:/tmp/api.oas3.json:ro
    ports:
      - '4000:8080'
    environment:
      SWAGGER_FILE: /tmp/api.oas3.json
  prism:
    container_name: prism-mock
    image: docker.io/stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.oas3.json'
    volumes:
      - ./api.oas3.json:/tmp/api.oas3.json:ro
    ports:
      - '4010:4010'

  # pgadmin:
  #   deploy:
  #     replicas: 0 # disable pgadmin
  #   container_name: pgadmin-server-dev
  #   image: dpage/pgadmin4:latest
  #   env_file:
  #     - .env
  #   environment:
  #     PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASSWORD:-postgres}
  #     PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL:-pg@pg.com}
  #   # restart: unless-stopped
  #   ports:
  #     - "5050:80"
  #     - "443:443"
  #   networks:
  #     - net-one

  # redis:
  #   container_name: redis-server-dev
  #   env_file:
  #     - .env
  #   ports:
  #     - "6379:6379"
