[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xtask"
path = "main.rs"

[dependencies]
clap = { version = "3.2", features = ["derive", "env", "unicode", "wrap_help", "cargo"]}
